const teachers = [
    "subhajit.adhikari@rcciit.org.in",
    "amit.khan@rcciit.org.in",
    "anjan.jana@rcciit.org.in",
    "abhijit.das@rcciit.org.in",
    "dipan.bandyopadhyay@rcciit.org.in",
    "soumyadip.dhar@rcciit.org.in",
    "ahana.patra@rcciit.org.in",
    "hrishikesh.bhaumik@rcciit.org.in",
    "jayanta.datta@rcciit.org.in",
    "soumen.mukherjee@rcciit.org.in",
    "pankaj.pal@rcciit.org.in",
    "sudarsan.biswas@rcciit.org.in",
    "indrajit.pan@rcciit.org.in",
    "hiranmoy.roy@rcciit.org.in",
    "jayanti.das@rcciit.org.in",
    "indronil.mazumder@rcciit.org.in",
    "abantika.choudhury@rcciit.org.in",
    "moumita.deb@rcciit.org.in",
    "srirupa.das@rcciit.org.in",
    "sharbari.kundu@rcciit.org.in",
    "monojit.manna@rcciit.org.in",
    "sujit.chakraborty@rcciit.org.in",
    "somnath.ghosh@rcciit.org.in",
    "nilanjan.maity@rcciit.org.in",
    "kamalika.banerjee@rcciit.org.in",
    "suman.basu@rcciit.org.in",
    "surajit.ghosh@rcciit.org.in"
]

export default teachers